version: '3.8'

services:
  app:
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:3091,http://localhost:3090
    ports:
      - "3090:3000"

  dashboard:
    build:
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3090/api/v1
        NEXT_PUBLIC_API_KEY: ${APP_SECRET}
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3090/api/v1
      - NEXT_PUBLIC_API_KEY=${APP_SECRET}
      - NEXTAUTH_URL=http://localhost:3091
    ports:
      - "3091:3000"
